### PR TITLE
Mutating with Radamsa

### LINKED ISSUE #15: Support mutating with Radamsa
Radamsa is an effective black-box fuzzer with a very simple API. tree-crasher should support mutating inputs with Radamsa, in addition to with tree-splicer.

https://docs.rs/radamsa/latest/radamsa/

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #15.

### CODE REVIEW

File: crates/tree-crasher/src/lib.rs [hunk 1]
```diff
@@ -177,60 +226,32 @@ fn job(
...
+    if files.is_empty() {
+        eprintln!("No files provided.");
+        return;
+    }
+    if args.radamsa {
+        let mut rng = rand::thread_rng();
+        let file_bytes: Vec<_> = files.values().map(|(bytes, _tree)| bytes).collect();
+        loop {
+            let bytes = file_bytes.get(rng.gen_range(0..files.len())).unwrap();
+            let mutant = radamsa::generate(bytes, None /* seed */, None /* max size */);
```
Comment (langston-barrett) [inline crates/tree-crasher/src/lib.rs:238]: Weirdly, this seems to work with `--debug`, but it exits the process without it. Backtrace:
```
#0  0x00007ffff7d11370 in exit ()
   from /nix/store/b2hc0i92l22ir2kavnjn3z5z6mzabbvm-glibc-2.34-210/lib/libc.so.6
#1  0x0000555555710bde in library_call ()
#2  0x0000555555710cfa in radamsa ()
#3  0x00005555556a06d6 in tree_crasher::job ()
```

Comment (langston-barrett) [reply crates/tree-crasher/src/lib.rs:238]: Presumably hitting this case: https://gitlab.com/akihe/radamsa/-/blob/df651a675e1c902ae2656891f3115c46c356bab1/c/lib.c#L22

Comment (langston-barrett) [reply crates/tree-crasher/src/lib.rs:238]: If I manually call `radamsa_init`, I instead get exists in:
```
#1  0x000055555566ef56 in get_obj_metrics ()
```
which I can't even find in the Radamsa source...

Comment (langston-barrett) [reply crates/tree-crasher/src/lib.rs]: Ah, I think Radamsa is just not thread-safe...
